### ISSUE TITLE
Typo in directive class name

### ISSUE THREAD

**Issue by AnvilStriker** [CoderAjay/ng2Draggable#14]
I hate to seem petty, but this really detracts from what's otherwise some beautiful code:

https://github.com/CoderAjay/ng2Draggable/blob/master/src/draggable.directive.ts#L12

Any chance of a correction before too many people have adopted?

Thanks!

**Comment by ajaysinghj8** [comment]
Hi @AnvilStriker,
the Class name should be Draggable rather DraggableDirective, is that so?

**Comment by AnvilStriker** [comment]
Sorry, I was referring to the stray 'r' that appears in 'Directive'.

It should be `DraggableDirective`, not `DraggableDirecrtive`.

Thanks.

**Comment by ajaysinghj8** [comment]
oh got that thanks, will fix that asap.

**Comment by AnvilStriker** [comment]
Thank you!

**Comment by ajaysinghj8** [comment]
It has been fixed, have a look. And please close the issue only if you think it is fixed properly.

**Comment by AnvilStriker** [comment]
Looks good to me. Thanks again.
