### ISSUE TITLE
Google recomends avoid libraries prefixed with ng2 or angular2

### ISSUE THREAD

**Issue by Steinmar** [CoderAjay/ng2Draggable#16]
In this article http://angularjs.blogspot.com/2016/12/ok-let-me-explain-its-going-to-be.html google recomends avoiding of naming libraries with ang2 or angular2 prefixes: "**Also, we should start avoiding GitHub/NPM libraries prefixed with ng2- or angular2-**".
So maybe you rename your repo while it isn't too late and a lot of developers don't use it.
For example I'll try to use it with angular 4.0.0. in my project and it starts making misunderstanding between angular and other third-party angular modules.

**Comment by ajaysinghj8** [comment]
Hi @Steinmar, 
  Thanks for this, I myself was thinking around it and you are right that ng2 doesn't making any sense here.  Will check with npm if we can change the name over there or will create a new npm package? Thank again will change the name asap and will let you know about. 

Also, what should be the name of this library, any suggestion on that?

**Comment by Steinmar** [comment]
Hello!
Thank you for your reply. You can't rename published npm module but you can mark is as deprecated with writing message that includes info about name of a new one and installation instructions . This message will see all users that will install your old package. Short info you can read on StackOverflow in this answer http://stackoverflow.com/a/28841779. And more detailed info is on official npm [documentation](https://www.npmjs.com/package/rename). So I think you'll not have any problems with current package users.

I think ngDraggable could be good name but it'is already exists. Maybe you should name it angular-draggable. There no such package in npm https://www.npmjs.com/search?q=angular-draggable&page=1&ranking=optimal. In my opinion two main words is draggable and angular so such name can be good sulution of naming problem.

**Comment by ajaysinghj8** [comment]
Thanks @Steinmar, 

Will do that asap.

**Comment by ajaysinghj8** [comment]
@Steinmar It's done, I have renamed the package, published it on npm with angular-draggable. Also, the ng2-draggable is deprecated now.  thanks you so much for the guidance, which make this possible in a very short amount of time.

Thanks Again.

**Comment by Steinmar** [comment]
@CoderAjay great! Thanks! I close this issue. And also I'll use your new one package in my project.
