### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by Steinmar** [CoderAjay/ng2Draggable#17]
Hi! After renaming your package there are few issues.
1. Your demo doesn't work. By this link I have some errors in console. It looks like you need to rebuild your app.
2.There is link to [https://coderajay.github.io/ng2Draggable/](old) demo in your project description and it returns 404.

![image](https://cloud.githubusercontent.com/assets/1280914/24567816/f2370948-1667-11e7-8447-aabdab25a147.png)

**Comment by ajaysinghj8** [comment]
@Steinmar  I need to rewrite example for it, it has not been updated from very long time.
