### ISSUE TITLE
Unable to install ng2-draggable

### ISSUE THREAD

**Issue by pritpalchahal** [CoderAjay/ng2Draggable#3]
## I am developing a mobile app using Ionic2 (Angular2, TypeScript). I need to implement DragnDrop functionality for touch devices, so I tried to install ng2-Draggable but it failed with the following console error:

_> ng2-draggable@0.0.5 postinstall /CollocationMatching/node_modules/ng2-draggable

> typings install

/usr/lib/node_modules/typings/node_modules/configstore/index.js:54
                throw err;
                ^

Error: EACCES: permission denied, open '/root/.config/configstore/typings.json'
You don't have access to this file.

```
at Error (native)
at Object.fs.openSync (fs.js:640:18)
at Object.fs.readFileSync (fs.js:508:33)
at Object.create.all.get (/usr/lib/node_modules/typings/node_modules/configstore/index.js:35:26)
at Object.Configstore (/usr/lib/node_modules/typings/node_modules/configstore/index.js:28:44)
at Object.<anonymous> (/usr/lib/node_modules/typings/node_modules/typings-core/dist/utils/store.js:5:19)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
```

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN enoent ENOENT: no such file or directory, open '/CollocationMatching/node_modules/typings/package.json'
npm WARN @angular/router@2.0.0-rc.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN @angular/router@2.0.0-rc.1 requires a peer of @angular/common@2.0.0-rc.1 but none was installed.
npm WARN @angular/router@2.0.0-rc.1 requires a peer of @angular/platform-browser@2.0.0-rc.1 but none was installed.
npm WARN @angular/router-deprecated@2.0.0-rc.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN @angular/router-deprecated@2.0.0-rc.1 requires a peer of @angular/common@2.0.0-rc.1 but none was installed.
npm WARN @angular/router-deprecated@2.0.0-rc.1 requires a peer of @angular/platform-browser@2.0.0-rc.1 but none was installed.
npm WARN @angular/upgrade@2.0.0-rc.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN @angular/upgrade@2.0.0-rc.1 requires a peer of @angular/compiler@2.0.0-rc.1 but none was installed.
npm WARN @angular/upgrade@2.0.0-rc.1 requires a peer of @angular/platform-browser@2.0.0-rc.1 but none was installed.
npm WARN collocationmatching@ No repository field.
npm WARN collocationmatching@ No license field.
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "ng2-draggable" "--save"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! ng2-draggable@0.0.5 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng2-draggable@0.0.5 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-draggable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-draggable
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-draggable
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /CollocationMatching/npm-debug.log_
## This is my system configuration:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS: Distributor ID: Ubuntu Description: Ubuntu 16.04 LTS 
Node Version: v6.3.0

Any help will be much appreciated as I do not have much time left till the end of the project. Thanks.

**Comment by ajaysinghj8** [comment]
It seems like you don't have permission to access this file '/root/.config/configstore/typings.json' , so what you can do you can try `sudo typings install`.  Let me know if this works.

**Comment by ajaysinghj8** [comment]
@pritpalchahal  i have updated it using angular2-rc5 with NgModule. Please try latest version of it and let me know if you face any issue.
