### ISSUE TITLE
Any plans to Update to RC.6 (Module Structure)?

### ISSUE THREAD

**Issue by TheBolmanator** [CoderAjay/ng2Draggable#5]
Ajay,  First I really like the code, you did a great job making very clean and readable.  I had thought I could refactor this to the current (Final Release) version of @Angular but, after a good bit of effort I have been striking out.  I was wondering if you might have some leanings you could share that might point me in the right direction.   I am using https://github.com/mgechev/angular-seed for my starting point.

**Comment by ajaysinghj8** [comment]
Hi, 
   First My apology for late reply. And about refactoring the this module, I am on to it, will publish it with in days.

Thanks.

**Comment by ajaysinghj8** [comment]
hi @TheBolmanator , I have update it to angular@2.4, please have a look. thanks.
