### ISSUE TITLE
Update release for Angular 2.0

### ISSUE THREAD

**Issue by ipoweb** [CoderAjay/ng2Draggable#6]
Could you update ng2Draggable for Angular 2.0 Final version ?

**Comment by ajaysinghj8** [comment]
Thanks, I am working on it.

**Comment by janko-sokolovic** [comment]
For some reason including import { DraggableModule }  from 'ng2-draggable';  doesnt find it. What could be the issue? using  angular 2.2.1

**Comment by nicholasguyett** [comment]
@jasofalcon, I'm not associated with this project, but in a project I contribute to, the issue was that the package does not contain the compiled JS files.  If your project is setup to bundle/reference the JS files, it will fail.

**Comment by krishnaisdinesh** [comment]
`import {DraggableModule} from 'ng2-draggable';`
While compiling getting error "ERROR in DraggableModule is not an NgModule"

When putting relative path
`import {DraggableModule} from '../../node_modules/ng2-draggable';`
Then also getting error.

**Comment by krishnaisdinesh** [comment]
Anyone help me out.. Thanks in advance.

**Comment by AnvilStriker** [comment]
@krishnaisdinesh -- I simply copied the contents of `node_modules/ng2-draggable/src/index.ts` to my project directory as `draggable.module.ts` and adjusted my import statements to import from `./`.

Yes, I know it's not a viable long-term strategy, but as I'm a complete n00b to Node, Typescript and Angular2, it's good enough for me for now.

That said, I'm hoping that @CoderAjay will be able to put a version on npmjs.com that will work straight out of the box.

**Comment by ajaysinghj8** [comment]
Hi @sireneweb, @jasofalcon, @nicholasguyett, @krishnaisdinesh and @AnvilStriker  thank you so much guys to the issue and discussion on it, my apologies for late response in this context finally
 able to fix it. Please have a look !!
