### ISSUE TITLE
draggable false not working

### ISSUE THREAD

**Issue by tobiasrighi** [CoderAjay/ng2Draggable#7]
It is supposed to disable draggable function when the parameter is false?
`<div [draggable]="false" style="position:fixed;">`
If yes, it is not working.

If it is not, can be made as an enhancement with default 'true'?
true:
`<div [draggable] style="position:fixed;">` or `<div [draggable]="true" style="position:fixed;">`
false:
`<div [draggable]="false" style="position:fixed;">`

**Comment by ajaysinghj8** [comment]
Hi @tobiasrighi ,

 I have implemented you suggestion in it. Thanks you so much to for this. 

Please have a  look and let me know what you think about.

**Comment by cacev000** [comment]
Hi @CoderAjay ,

I am trying to use this feature as mentioned by @tobiasrighi and i am not able to make it work.

in **html** file i have the following

`<div [draggable]="isDraggable">`

where the variable "isDraggable" will be toggled between true and false in the **ts** file.

please let me know if this has been fixed.

Thank you

**Comment by ajaysinghj8** [comment]
Hi @cacev000,

  The issue has been fixed and you can use this as  
```html
  <div draggable="true">
  </div>

   <div draggable="false">
  </div>

```  

Thanks.
