### ISSUE TITLE
DraggableModule is not an NgModule

### ISSUE THREAD

**Issue by jredd** [CoderAjay/ng2Draggable#8]
I'm using angular cli v1.0.0-beta.26 and angular 2.3.1. When the page loads it just tells me the DraggableModule is not an NgModule

**Comment by ajaysinghj8** [comment]
Hi @jredd, I have fixed that please have a look. thanks

**Comment by ajaysinghj8** [comment]
I am closing this issue, if you feel like this issue should not be closed please reopen it.
